export type FeaturedCar = {
  id: number;
  make: string;
  model: string;
  year: number;
  price: number;
  images: string[];
  transmission: string;
  fuelType: string;
  bodyType: string;
  mileage: number;
  color: string;
  wishlisted: boolean;
};

export const featuredCars = [
  {
    id: 1,
    make: "Tesla",
    model: "Model S",
    year: 2023,
    price: 89999,
    images: ["/cars/model-s.avif"],
    transmission: "Automatic",
    fuelType: "Electric",
    bodyType: "Sedan",
    mileage: 5000,
    color: "Silver",
    wishlisted: false,
  },
  {
    id: 2,
    make: "Ford",
    model: "Mustang GT",
    year: 2022,
    price: 55999,
    images: ["/cars/mustang-gt.avif"],
    transmission: "Manual",
    fuelType: "Petrol",
    bodyType: "Coupe",
    mileage: 12000,
    color: "Blue",
    wishlisted: true,
  },
  {
    id: 3,
    make: "Porsche",
    model: "911 Carrera",
    year: 2023,
    price: 112999,
    images: ["/cars/911-carrera.jpg"],
    transmission: "Automatic",
    fuelType: "Petrol",
    bodyType: "Coupe",
    mileage: 3000,
    color: "Black",
    wishlisted: false,
  },
  {
    id: 4,
    make: "Honda",
    model: "Civic Type R",
    year: 2023,
    price: 42999,
    images: ["/cars/civic-r.jpg"],
    transmission: "Manual",
    fuelType: "Diesel",
    bodyType: "Hatchback",
    mileage: 7000,
    color: "White",
    wishlisted: false,
  },
  {
    id: 5,
    make: "Lamborghini",
    model: "Aventador",
    year: 2021,
    price: 399999,
    images: ["/cars/aventador.avif"],
    transmission: "Automatic",
    fuelType: "Petrol",
    bodyType: "Supercar",
    mileage: 1000,
    color: "Silver",
    wishlisted: true,
  },
  {
    id: 6,
    make: "Mercedes-Benz",
    model: "G-Wagon",
    year: 2023,
    price: 159999,
    images: ["/cars/g-wagon.jpg"],
    transmission: "Automatic",
    fuelType: "Diesel",
    bodyType: "SUV",
    mileage: 6000,
    color: "Black",
    wishlisted: false,
  },
  {
    id: 7,
    make: "BMW",
    model: "i8 Coupe",
    year: 2020,
    price: 99999,
    images: ["/cars/bmw-i8.jpg"],
    transmission: "Automatic",
    fuelType: "Hybrid",
    bodyType: "Coupe",
    mileage: 15000,
    color: "Silver",
    wishlisted: false,
  },
  {
    id: 8,
    make: "Chevrolet",
    model: "Camaro ZL1",
    year: 2022,
    price: 67999,
    images: ["/cars/camaro-zl1.avif"],
    transmission: "Manual",
    fuelType: "Petrol",
    bodyType: "Coupe",
    mileage: 9000,
    color: "Blue",
    wishlisted: true,
  },
  {
    id: 9,
    make: "Audi",
    model: "R8 V10",
    year: 2023,
    price: 169999,
    images: ["/cars/audi-r8.jpg"],
    transmission: "Automatic",
    fuelType: "Petrol",
    bodyType: "Coupe",
    mileage: 4000,
    color: "Gray",
    wishlisted: false,
  },
  {
    id: 10,
    make: "Bugatti",
    model: "Chiron",
    year: 2022,
    price: 2999999,
    images: ["/cars/chiron.avif"],
    transmission: "Automatic",
    fuelType: "Petrol",
    bodyType: "Hypercar",
    mileage: 1200,
    color: "Black",
    wishlisted: true,
  },
];
